[aws]
# ここにAWS認証情報を設定します（実際のデプロイ時にStreamlit Cloudの設定で追加します）
aws_access_key_id = "YOUR_AWS_ACCESS_KEY"
aws_secret_access_key = "YOUR_AWS_SECRET_KEY"
region_name = "ap-northeast-1"  # 使用しているリージョン
table_name = "streamlit-chatbot-messages"
